name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Check format
        run: npm run check-format

      - name: Test
        run: npm run test

      - name: Argos upload screenshots
        run: npx argos upload cypress/screenshots
        env:
          ARGOS_TOKEN: ${{ secrets.ARGOS_TOKEN }}
